http:
  port: 3004
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  bicycle:
    host: localhost
    paths: ["/api/bicycles/", "/api/bicycles/*"]
  location:
    host: localhost
    paths: ["/api/locations/", "/api/locations/*"]
  auth:
    host: localhost
    paths: ["/auth", "/auth/*"]
serviceEndpoints:
  httpbin:
    url: 'localhost:3001/bicycles'
  bicycleService:
    url: 'http://localhost:3001'
  locationService:
    url: 'http://localhost:3002'
  authService:
    url: 'http://localhost:3005'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - request-transformer
  - jwt
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  bicyclePipeline:
    apiEndpoints:
      - bicycle
    policies:
      - proxy:
          - action:
              serviceEndpoint: bicycleService 
              changeOrigin: true
  locationPipeline:
    apiEndpoints:
      - location
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: locationService 
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authService 
              changeOrigin: true